- platform: trend
  sensors:
    ph_rank_trend:
      entity_id: sensor.ph_ranking_scrape
      invert : true
      max_samples: 6

- platform: wyzesense
  device: auto

- platform: octoprint
  monitored_conditions:
    - Printing
    - Printing Error

- platform: ffmpeg_motion
  input: !secret wyze_address
  name: wyze_motion
  changes: 2

- platform: template
  sensors:
      apple_tv_paused:
        value_template: >-
          {{ is_state('media_player.apple_tv', 'paused') }}
        delay_on:
          minutes: 30
