- platform: trend
  sensors:
    ph_rank_trend:
      entity_id: sensor.ph_ranking_scrape
      invert : true
      max_samples: 6

    mv_rank_trend:
      entity_id: sensor.mv_rank_scrape
      invert : true
      max_samples: 6

- platform: wyzesense
  device: auto

- platform: octoprint
  monitored_conditions:
    - Printing
    - Printing Error

- platform: ffmpeg_motion
  input: !secret west_camera_rtsp
  name: west_camera_motion
  changes: 1

- platform: ffmpeg_motion
  input: !secret east_camera_rtsp
  name: east_camera_motion
  changes: 1

- platform: ffmpeg_motion
  input: !secret print_camera_rtsp
  name: print_camera_motion
  changes: 1

- platform: template
  sensors:
      apple_tv_paused:
        value_template: >-
          {{ is_state('media_player.apple_tv', 'paused') }}
        delay_on:
          minutes: 30
      new_release:
        value_template: "{{ states('sensor.current_version') != states('sensor.release') }}"
        icon_template: mdi:arrow-up-bold-circle-outline
      bed_right_invert:
          value_template: "{{ is_state('binary_sensor.bed_right', 'off') }}"
      bed_left_invert:
          value_template: "{{ is_state('binary_sensor.bed_left', 'off') }}"