- platform: netgear
  ssl: False
  host: !secret router_ip
  password: !secret netgear_password
  interval_seconds: 30
  consider_home: 300
  new_device_defaults:
    track_new_devices: False
- platform: iphonedetect
  consider_home: 60
  new_device_defaults:
    track_new_devices: true
  hosts:
    armond_iphone: 192.168.0.27
    madison_iphone: 192.168.0.5