- platform: html5
  name: HTML5
  vapid_pub_key: !secret vapid_pub_key
  vapid_prv_key: !secret vapid_prv_key
  vapid_email: !secret email
    
- name: twilio
  platform: twilio_sms
  from_number: !secret twilio_number

- platform: webostv
  host: !secret lg_tv_ip
  name: living_room_tv_lgos
  filename: webostv.conf

- platform: hass_agent_notifier
  name: "Desktop HASS.Agent"
  resource: http://192.168.0.3:5115/notify