- platform: wake_on_lan
  mac: !secret desktop_mac
  name: "Desktop"
  host: !secret desktop_ip
  broadcast_address: !secret desktop_ip
  turn_off:
    service: script.turn_off_pc
    
- platform: template
  switches:
    tv_state:
      value_template: "{{ not is_state('media_player.living_room_tv', 'off') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.living_room_tv
      turn_off:
        service: script.turn_off_tv
        
    aquarium:
      value_template: "{{ is_state('switch.aquarium_day', 'on') }}"
      turn_on:
        - service: switch.turn_on
          entity_id: switch.aquarium_day
        - service: switch.turn_off
          entity_id: switch.aquarium_night
      turn_off:
        - service: switch.turn_off
          entity_id: switch.aquarium_day
        - service: switch.turn_on
          entity_id: switch.aquarium_night