- platform: wake_on_lan
  mac: !secret desktop_mac
  name: "Desktop"
  host: !secret desktop_ip
  broadcast_address: !secret desktop_ip
  turn_off:
    service: script.turn_off_pc
    
- platform: template
###TODO###
  switches:
#    tv_state:
#      value_template: "{{ not is_state('media_player.living_room_tv', 'off') }}"
#      turn_on:
#        service: media_player.turn_on
#        data:
#          entity_id: media_player.living_room_tv
#      turn_off:
#        service: script.turn_off_tv
        
    aquarium:
      value_template: "{{ is_state('light.aquarium_day', 'on') }}"
      turn_on:
        - service: light.turn_on
          entity_id: light.aquarium_day
        - service: light.turn_off
          entity_id: light.aquarium_night
      turn_off:
        - service: light.turn_off
          entity_id: light.aquarium_day
        - service: light.turn_on
          entity_id: light.aquarium_night
    bathroom_fan:
      value_template: "{{ is_state('light.bathroom_fan', 'on') }}"
      turn_on:
        - service: light.turn_on
          target:
            entity_id: light.bathroom_fan
      turn_off:
        - service: light.turn_off
          target:
            entity_id: light.bathroom_fan
    aquarium_sludge_control:
      value_template: "{{ is_state('light.aquarium_sludge_control', 'on') }}"
      turn_on:
        - service: light.turn_on
          target:
            entity_id: light.aquarium_sludge_control
      turn_off:
        - service: light.turn_off
          target:
            entity_id: light.aquarium_sludge_control