- platform: wake_on_lan
  mac: !secret desktop_mac
  name: "Desktop"
  host: !secret desktop_ip
  broadcast_address: !secret desktop_ip
  turn_off:
    service: script.turn_off_pc
    
- platform: template
  switches:
    tv_state:
      value_template: "{{ not is_state('media_player.living_room_tv', 'off') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.living_room_tv
      turn_off:
        service: script.turn_off_tv
        
    aquarium:
      value_template: "{{ is_state('switch.aquarium_day', 'on') }}"
      turn_on:
        - service: switch.turn_on
          entity_id: switch.aquarium_day
        - service: switch.turn_off
          entity_id: switch.aquarium_night
      turn_off:
        - service: switch.turn_off
          entity_id: switch.aquarium_day
        - service: switch.turn_on
          entity_id: switch.aquarium_night

    living_room_ac_cool:
      value_template: "{{ is_state('input_boolean.living_room_ac_cool', 'on') }}"
      turn_on:
        - service: script.turn_on_living_room_ac_cool
        - service: input_boolean.turn_on
          entity_id: input_boolean.living_room_ac_cool
      turn_off:
        - service: script.turn_off_living_room_ac_cool
        - service: input_boolean.turn_off
          entity_id: input_boolean.living_room_ac_cool

    living_room_ac_fan:
      value_template: "{{ is_state('input_boolean.living_room_ac_fan', 'on') }}"
      turn_on:
        - service: script.turn_on_living_room_ac_fan
        - service: input_boolean.turn_on
          entity_id: input_boolean.living_room_ac_fan
      turn_off:
        - service: script.turn_off_living_room_ac_fan
        - service: input_boolean.turn_off
          entity_id: input_boolean.living_room_ac_fan

    bedroom_ac_cool:
      value_template: "{{ is_state('input_boolean.bedroom_ac_cool', 'on') }}"
      turn_on:
        - service: script.turn_on_bedroom_ac_cool
        - service: input_boolean.turn_on
          entity_id: input_boolean.bedroom_ac_cool
      turn_off:
        - service: script.turn_off_bedroom_ac_cool
        - service: input_boolean.turn_off
          entity_id: input_boolean.bedroom_ac_cool

    bedroom_ac_fan:
      value_template: "{{ is_state('input_boolean.bedroom_ac_fan', 'on') }}"
      turn_on:
        - service: script.turn_on_bedroom_ac_fan
        - service: input_boolean.turn_on
          entity_id: input_boolean.bedroom_ac_fan
      turn_off:
        - service: script.turn_off_bedroom_ac_fan
        - service: input_boolean.turn_off
          entity_id: input_boolean.bedroom_ac_fan