####################################
#       System Configuration       #
####################################
homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config/images

#http:
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

config:

logbook:

map:

person:

mobile_app:

ssdp:

zeroconf:

sun:

history:

system_health:

discovery:

cloud:

media_source:

image:

my:

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/custom-sidebar/custom-sidebar.js
    - /local/custom_icons.js

recorder:
  db_url: !secret db_url
  purge_keep_days: 367

####################################
#          Folder Includes         #
####################################
group: !include integrations/group.yaml
automation: !include_dir_merge_list automation
script: !include_dir_merge_named script
#scene: !include scenes.yaml
sensor: !include integrations/sensor.yaml
ios: !include integrations/ios_config.yaml
input_select: !include integrations/input_select.yaml
device_tracker: !include integrations/device_tracker.yaml
input_boolean: !include integrations/input_boolean.yaml
input_text: !include integrations/input_text.yaml
input_datetime: !include integrations/input_datetime.yaml
input_number: !include integrations/input_number.yaml
binary_sensor: !include integrations/binary_sensor.yaml
notify: !include integrations/notify.yaml
switch: !include integrations/switch.yaml
var: !include integrations/var.yaml
light: !include integrations/light.yaml
rest_command: !include integrations/rest_command.yaml
timer: !include integrations/timer.yaml

####################################
#        Manual Integrations       #
####################################
spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

breaking_changes:

stream:

wemo:
#  discovery: false
#  static:
#    - 192.168.0.13
#    - 192.168.0.14
#    - 192.168.0.15
#    - 192.168.0.16

smartthinq:
  token: !secret lg_refresh_token
  region: US
  language: en-US

tts:
  - platform: google_translate
#    base_url: !secret local_base_url

apple_tv:
  - host: !secret apple_tv_ip
    login_id: !secret apple_tv_login_id

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    arming_time: 60
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0

#climate:
#  - platform: generic_thermostat
#    name: Living Room
#    heater: switch.living_room_ac_cool
#    target_sensor: sensor.coat_closet_sensor_temperature
#    ac_mode: true
#    keep_alive:
#      minutes: 10
#    min_cycle_duration:
#      minutes: 2
#  - platform: generic_thermostat
#    name: Bedroom
#    heater: switch.bedroom_ac_cool
#    target_sensor: sensor.bedroom_closet_sensor_temperature
#    ac_mode: true
#    keep_alive:
#      minutes: 10
#    min_cycle_duration:
#      minutes: 2

sonoff:
  username: !secret sonoff_email
  password: !secret sonoff_password
  reload: always
  default_class: light

#cSpell:disable
nintendo_wishlist:
  country: US
  wishlist:
    - FAST RMX
    - Return of the Obra Dinn
    - "The Experiment: Escape Room"
    - Superliminal
    - STAR WARS Episode I Racer
    - Undertale
    - Untitled Goose Game
    - Overcooked Special Edition
    - Katamari Damacy REROLL
    - "The Legend of Zelda: Link’s Awakening"
    - "Phoenix Wright: Ace Attorney Trilogy"
    - Spyro Reignited Trilogy
    - Superliminal
    - Kirby Star Allies
    - Super Mario Odyssey
    - New Super Mario Bros. U Deluxe
    - The Jackbox Party Pack
    - Luigi’s Mansion 3
    - Overcooked! 2
    - Cuphead

#cSpell:enable

#shell_command:
#  delete_gtfs: rm gtfs/google_transit.sqlite

#downloader:
#  download_dir: gtfs
    
updater:
  include_used_components: true

logger:
  default: warning
  logs:
    # log level for HA core
    homeassistant.core: debug

browser_mod:
  devices:
    057ccd42-f31faaea:
      name: Desktop
      camera: true
    89b8efe5_85346523:
      name: Personal Work
      camera: true
    0cedc2eb-d5dca07b:
      name: Madison's iPhone

wake_on_lan:

webostv:
  host: !secret lg_tv_ip
  name: Living Room TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret lg_tv_mac
      broadcast_address: !secret lg_tv_ip
  customize:
    sources:
      - livetv
      - youtube
      - amazon
      - netflix

camera:
  - platform: ffmpeg
    name: Printer Camera
    input: !secret print_camera_rtsp
    extra_arguments: "-vf 'rotate=0.5'"
  - platform: ffmpeg
    name: West Camera
    input: !secret west_camera_rtsp
  - platform: ffmpeg
    name: East Camera
    input: !secret east_camera_rtsp
#  - platform: local_file
#    file_path: /config/images/mail_and_packages/mail_today.gif
#    name: mail_usps
  - platform: unsplash
    api_key: !secret unsplash_access_key
    orientation: landscape
  - platform: mjpeg
    name: CR-X OctoPrint
    still_image_url: http://octopi-cr-x.local/webcam/?action=snapshot
    mjpeg_url: http://octopi-cr-x.local/webcam/?action=stream
  - platform: mjpeg
    name: DaVinci OctoPrint
    still_image_url: http://octopi-xyz.local/webcam/?action=snapshot
    mjpeg_url: http://octopi-xyz.local/webcam/?action=stream

twilio:
  account_sid: !secret twilio_sid
  auth_token: !secret twilio_token

#microsoft_face:
#  api_key: !secret microsoft_face_api_key
#  azure_region: northcentralus
#  
#image_processing:
#  - platform: microsoft_face_detect
#    scan_interval: 9999
#    source:
#      - entity_id: camera.wyze_cam
#  - platform: microsoft_face_identify
#    group: all
#    scan_interval: 9999
#    source:
#      - entity_id: camera.wyze_cam

google:
  client_id: !secret google_id
  client_secret: !secret google_secret
    
#icloud:
#  - username: !secret old_apple_email
#    password: !secret apple_password

noonlight:
  id: !secret noonlight_id
  secret: !secret noonlight_secret
  api_endpoint: https://api.noonlight.com/platform/v1
  token_endpoint: https://noonlight.konnected.io/ha/token
    
#google_assistant:
#  service_account: !include SERVICE_ACCOUNT.json
#  project_id: !secret google_assistant_project_id
#  report_state: true
#  exposed_domains:
#    - script
    
counter:
  meds_counter:
    minimum: 0
    
#conversation:
#  intents: !include integrations/intent.yaml
  
#intent_script: !include integrations/intent_script.yaml

panel_iframe:
  logs:
    title: Logs
    icon: mdi:math-log
    url: !secret logs_url
#  foldingathome:
#    title: Folding@home
#    icon: mdi:bacteria-outline
#    url: !secret folding_url
#  bitwarden:
#    title: Bitwarden
#    icon: mdi:shield-half-full
#    url: !secret bitwarden_url
#  octoprint:
#    title: CR-X OctoPrint
#    icon: mdi:printer-3d
#    url: http://octopi-cr-x.local/

octoprint:
  - host: !secret cr_x_octoprint_host
    bed: true
    ssl: false
    api_key: !secret octoprint_api_key
    name: CR-X
    number_of_tools: 2
  - host: !secret xyz_octoprint_host
    bed: true
    ssl: false
    api_key: !secret xyz_octoprint_api_key
    name: DaVinci Nano
    number_of_tools: 1