####################################
#       System Configuration       #
####################################
homeassistant:
  whitelist_external_dirs:
    - /config/images

config:

logbook:

map:

person:

mobile_app:

ssdp:

zeroconf:

sun:

history:

system_health:

discovery:

frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest
  extra_module_url:
    - /hacsfiles/custom-sidebar/custom-sidebar.js

recorder:
  db_url: !secret db_url
  purge_keep_days: 367

####################################
#          Folder Includes         #
####################################
group: !include integrations/group.yaml
automation: !include_dir_merge_list automation
script: !include_dir_merge_named script
#scene: !include scenes.yaml
sensor: !include integrations/sensor.yaml
ios: !include integrations/ios_config.yaml
input_select: !include integrations/input_select.yaml
device_tracker: !include integrations/device_tracker.yaml
input_boolean: !include integrations/input_boolean.yaml
input_datetime: !include integrations/input_datetime.yaml
input_number: !include integrations/input_number.yaml
binary_sensor: !include integrations/binary_sensor.yaml
notify: !include integrations/notify.yaml
switch: !include integrations/switch.yaml
var: !include integrations/var.yaml
light: !include integrations/light.yaml
rest_command: !include integrations/rest_command.yaml

####################################
#        Manual Integrations       #
####################################
spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

breaking_changes:

smartthinq:
    token: !secret lg_refresh_token
    region: US
    language: en-US

tts:
  - platform: google_translate
    base_url: !secret local_base_url

apple_tv:
  - host: !secret apple_tv_ip
    login_id: !secret apple_tv_login_id

climate:
  - platform: generic_thermostat
    name: Living Room
    heater: switch.living_room_ac_cool
    target_sensor: sensor.coat_closet_sensor_temperature
    ac_mode: true
    keep_alive:
      minutes: 10
    min_cycle_duration:
      minutes: 2
  - platform: generic_thermostat
    name: Bedroom
    heater: switch.bedroom_ac_cool
    target_sensor: sensor.bedroom_closet_sensor_temperature
    ac_mode: true
    keep_alive:
      minutes: 10
    min_cycle_duration:
      minutes: 2

sonoff:
  username: !secret sonoff_email
  password: !secret sonoff_password
  reload: always
  default_class: light

shell_command:
  delete_gtfs: rm gtfs/google_transit.sqlite

airvisual:
    api_key: !secret airvisual_api_key
    geographies:
        latitude: !secret home_lat
        longitude: !secret home_lon

downloader:
  download_dir: gtfs
    
timer:
  laundry:
    duration: '00:49:00'
  dryer:
    duration: '00:45:00'
    
updater:
  include_used_components: true
  
logger:
  default: warning

browser_mod:
  devices:
    ebd9cb56-e768f3d4:
      name: Desktop
      camera: true
    c2208e85-9429800f:
      name: Madison's iPhone

camera:
  - platform: generic
    name: WYZE Cam
    still_image_url: !secret wyze_still_image
    stream_source: !secret wyze_rtsp
  - platform: local_file
    file_path: /config/images/mail_and_packages/mail_today.gif
    name: mail_usps
  - platform: unsplash
    api_key: !secret unsplash_access_key
    orientation: landscape

twilio:
  account_sid: !secret twilio_sid
  auth_token: !secret twilio_token

#microsoft_face:
#  api_key: !secret microsoft_face_api_key
#  azure_region: northcentralus
#  
#image_processing:
#  - platform: microsoft_face_detect
#    scan_interval: 9999
#    source:
#      - entity_id: camera.wyze_cam
#  - platform: microsoft_face_identify
#    group: all
#    scan_interval: 9999
#    source:
#      - entity_id: camera.wyze_cam

google:
  client_id: !secret google_id
  client_secret: !secret google_secret
    
icloud:
  - username: !secret email
    password: !secret apple_password
    
google_assistant:
  service_account: !include SERVICE_ACCOUNT.json
  project_id: !secret google_assistant_project_id
  report_state: true
  exposed_domains:
    - script
    
counter:
  meds_counter:
    minimum: 0
    
#conversation:
#  intents: !include integrations/intent.yaml
  
#intent_script: !include integrations/intent_script.yaml

#panel_iframe:
#  foldingathome:
#    title: Folding@home
#    icon: mdi:bacteria-outline
#    url: !secret folding_url
#  bitwarden:
#    title: Bitwarden
#    icon: mdi:shield-half-full
#    url: !secret bitwarden_url
#  octoprint:
#    title: OctoPrint
#    icon: mdi:printer-3d
#    url: !secret octoprint_host

#octoprint:
#  host: !secret octoprint_host
#  port:
#  ssl: true
#  api_key: !secret octoprint_api_key
#  name: da Vinci nano
#  number_of_tools: 1