- alias: Announce time
  mode: restart
  trigger:
    platform: time_pattern
    hours: '*'
  condition:
    condition: state
    entity_id: input_boolean.announce_time
    state: 'on'
  action:
    - service: media_player.turn_on
      entity_id: media_player.office_speaker
    - wait_template: "{{ is_state('media_player.office_speaker', 'idle') }}"
    - service: var.set
      data:
        entity_id: var.volume_temp
        value_template: "{{ state_attr('media_player.office_speaker', 'volume_level')| float | round(2)}}"
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.office_speaker
        volume_level: 0.6
    - service: tts.cloud_say
      data:
        entity_id: media_player.office_speaker
        message: >-
          It is now {{ (now().timestamp()|float )|timestamp_custom('%-H') }} {{ "hours" if (now().timestamp()|float )|timestamp_custom('%-H')|int != 1 else "hour" }}
    - wait_template: "{{ is_state('media_player.office_speaker', 'playing') }}"
      timeout: "00:02:00"
    - wait_template: "{{ is_state('media_player.office_speaker', 'idle') }}"
      timeout: "00:02:00"
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.office_speaker
        volume_level: "{{ states('var.volume_temp')| float }}"
    - service: media_player.turn_off
      entity_id: media_player.office_speaker