- alias: Arm security alarm
  mode: restart
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'arming'
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'pending'
  action:
    - service: media_player.turn_on
      entity_id: media_player.all_devices
    - wait_template: "{{ is_state('media_player.all_devices', 'idle') }}"
    - service: var.set
      data:
        entity_id: var.volume_temp
        value_template: "{{ state_attr('media_player.all_devices', 'volume_level')| float | round(2)}}"
    - service: media_player.volume_set
      data:
        entity_id: media_player.all_devices
        volume_level: 0.3
    - service: media_player.play_media
      data:
        entity_id: media_player.all_devices
        media_content_id: 'http://192.168.0.2:8123/local/audio/arming.mp3'
        media_content_type: music
    - wait_template: "{{ is_state('media_player.all_devices', 'idle') }}"
      timeout: "00:02:00"
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.all_devices
        volume_level: "{{ states('var.volume_temp')| float }}"
    - service: media_player.turn_off
      entity_id: media_player.all_devices
    - wait_for_trigger:
        - platform: state
          entity_id: alarm_control_panel.home_alarm
          to: 'armed_away'
        - platform: state
          entity_id: alarm_control_panel.home_alarm
          to: 'armed_home'
    - service: notify.mobile_app_madisons_iphone
      data:
        title: "Armed"
        message: "The security system is now armed"
        data:
          apns_headers:
            'apns-collapse-id': 'alarm'
          push:
            sound: 'door_lock.wav'
            thread-id: "alarm"
    - service: notify.mobile_app_iphone
      data:
        title: "Armed"
        message: "The security system is now armed"
        data:
          apns_headers:
            'apns-collapse-id': 'alarm'
          push:
            sound: 'door_lock.wav'
            thread-id: "alarm"