- alias: Set aurora brightness on sun position
  trigger:
    - platform: state
      entity_id: sun.sun
    - platform: state
      entity_id: light.nanoleaf
      to: 'on'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.aurora_brightness
        option: >-
          {% if is_state("sun.sun", "above_horizon") %}
          Bright
          {% else %}
          Dim
          {% endif %}