- alias: Update aurora effect based on input select
  trigger:
    - platform: state
      entity_id: input_select.aurora_effects
  action:
    service: light.turn_on
    data_template:
      entity_id: light.nanoleaf
      effect: "{{ states('input_select.aurora_effects') }}"
      brightness: "{{ states('sensor.aurora_brightness_map')|int }}"