- alias: Update aurora select to off
  mode: restart
  trigger:
    - platform: state
      entity_id: light.nanoleaf
      to: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.aurora_brightness
        option: 'Off'