- alias: Auto alarm
  trigger:
    - platform: state
      entity_id: sensor.auto_alarm_trigger
      to: 'True'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.awake
        state: 'off'
      - condition: state
        entity_id: input_boolean.sleeping_in
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.uptime
        above: 0.1
  action:
#    - delay:
#        minutes: >-
#          {{ ((1 - ((((now().timestamp() - (states('var.time_asleep') | int)) / 3600) | int) / 8)) * 30) | int }}
#    - condition: state
#      entity_id: input_boolean.awake
#      state: 'off'
    - service: hue.hue_activate_scene
      data:
        group_name: "Bedroom"
        scene_name: "Dimmed"
    - delay:
        seconds: 10
    - service: light.turn_off
      entity_id: light.bedroom_4
    - delay:
        minutes: 2
    - service: automation.trigger
      entity_id: automation.aurora_controller_hourly
    - service: script.wake_up
#    - delay:
#        minutes: 20
#    - condition: template
#      value_template: "{{ (as_timestamp(state_attr('script.wake_up','last_triggered')) | float > as_timestamp(state_attr('binary_sensor.shower_motion','timestamp')) | float) and is_state('input_boolean.sleeping_in','off') }}"
#    - service: script.wake_up