- alias: Auto alarm
  trigger:
    - platform: state
      entity_id: sensor.auto_alarm_trigger
      to: "True"
  condition:
    - condition: state
      entity_id: input_boolean.awake
      state: 'off'
  action:
    - delay:
        minutes: >-
          {{ ((1 - ((((now().timestamp() - (states('var.time_asleep') | int)) / 3600) | int) / 8)) * 30) | int }}
    - condition: state
      entity_id: input_boolean.awake
      state: 'off'
    - service: hue.hue_activate_scene
      data:
        group_name: "Bedroom"
        scene_name: "Dimmed"
    - delay:
        seconds: 10
    - service: light.turn_off
      entity_id: light.bedroom_4
    - delay:
        minutes: 2
    - service: automation.trigger
      entity_id: automation.aurora_controller
    - service: script.wake_up