- alias: Auto alarm
  mode: restart
  trigger:
    - platform: state
      entity_id: sensor.auto_alarm_trigger
      to: 'True'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.awake
        state: 'off'
      - condition: state
        entity_id: input_boolean.sleeping_in
        state: 'off'
      - condition: state
        entity_id: script.set_nap
        state: 'off'
  action:
#    - delay:
#        minutes: >-
#          {{ ((1 - ((((now().timestamp() - (states('var.time_asleep') | int)) / 3600) | int) / 8)) * 30) | int }}
#    - condition: state
#      entity_id: input_boolean.awake
#      state: 'off'
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.home_alarm
        code: !secret alarm_code
    - service: hue.hue_activate_scene
      data:
        group_name: "Bedroom"
        scene_name: "Dimmed"
    - delay:
        seconds: 1
    - service: light.turn_off
      entity_id: light.bedroom_lights
    - delay:
        minutes: 2
    - condition: state
      entity_id: input_boolean.awake
      state: 'off'
    - condition: state
      entity_id: input_boolean.sleeping_in
      state: 'off'
    - service: automation.trigger
      entity_id: automation.aurora_controller_hourly
    - service: script.wake_up
    - condition: state
      entity_id: person.armond
      state: 'not_home'
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_ac_mode
        option: Fan
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_ac_fan_mode
        option: Low
#    - delay:
#        minutes: 20
#    - condition: template
#      value_template: "{{ (as_timestamp(state_attr('script.wake_up','last_triggered')) | float > as_timestamp(state_attr('binary_sensor.shower_motion','timestamp')) | float) and is_state('input_boolean.sleeping_in','off') }}"
#    - service: script.wake_up