- alias: Change bedroom ac to off based on input select
  mode: restart
  trigger:
    - platform: state
      entity_id: input_select.bedroom_ac_mode
      to: "Off"
  action:
    - service: rest_command.turn_off_bedroom_ac

- alias: Change bedroom ac to cool based on input select
  mode: restart
  trigger:
    - platform: state
      entity_id: input_select.bedroom_ac_mode
      to: "Cool"
  action:
    - service: rest_command.turn_on_bedroom_ac
    - service: rest_command.bedroom_ac_mode
    - service: rest_command.bedroom_ac_fan_mode
    - service: rest_command.bedroom_ac_temperature_set

- alias: Change bedroom ac to fan based on input select
  mode: restart
  trigger:
    - platform: state
      entity_id: input_select.bedroom_ac_mode
      to: "Fan"
  action:
    - service: rest_command.turn_on_bedroom_ac
    - service: rest_command.bedroom_ac_mode
    - service: rest_command.bedroom_ac_fan_mode

- alias: Change bedroom ac to dry based on input select
  mode: restart
  trigger:
    - platform: state
      entity_id: input_select.bedroom_ac_mode
      to: "Dry"
  action:
    - service: rest_command.turn_on_bedroom_ac
    - service: rest_command.bedroom_ac_mode
    - service: rest_command.bedroom_ac_fan_mode
    - service: rest_command.bedroom_ac_temperature_set