- alias: Send iOS notification when battery is low
  mode: restart
  trigger:
    platform: state
    entity_id: sensor.charge_battery_trigger
    to: "True"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.battery_state
        state: 'Not Charging'
      - condition: numeric_state
        entity_id: sensor.madisons_iphone_battery_level
        below: 85
      - condition: template
        value_template: "{{ as_timestamp(states.sensor.madisons_iphone_battery_state_app.last_changed) > as_timestamp(state_attr('automation.send_ios_notification_when_battery_is_low','last_triggered')) }}"
  action:
    - service: notify.mobile_app_madisons_iphone
      data_template:
        message: "Your battery is at {{ states('sensor.battery_level') }}%. You may want to charge it before {{ state_attr('calendar.personal_trigger','message') }}."
        data:
          group: "charge-reminder"
          tag: "charge-reminder"
          push:
            sound: 'low_power.caf'