- alias: CR-X Print Complete Notification
  mode: parallel
  trigger:
    - platform: state
      entity_id:
        - sensor.cr_x_time_remaining
      to: '0'
  condition:
    condition: state
    entity_id: input_boolean.awake
    state: 'on'
  action:
    - service: notify.mobile_app_madisons_iphone
      data_template:
        title: "CR-X Complete"
        message: "The print on the CR-X has finished"
        data:
          group: "cr-x-complete"
          tag: "cr-x-complete"
          push:
            sound: 'file_done.wav'