- alias: Send notification if I there is a cubs cage
  mode: restart
  trigger:
    - platform: state
      entity_id: sensor.google_cal_leave_trigger_madison
      to: "True"
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.travel_mode_madison
      state: 'Transit'
    - condition: state
      entity_id: input_boolean.staying_home_madison
      state: 'off'
    - condition: template
      value_template: "{{ 'YES' in states('sensor.cubs_result') }}"
  action:
    - delay:
        minutes: 2
    - condition: state
      entity_id: input_select.travel_mode_madison
      state: 'Transit'
    - service: notify.mobile_app_madisons_iphone
      data:
        message: "Note: There is a cubs game today."
        data:
          group: "cubs-reminder"
          tag: "cubs-reminder"
          push:
            sound: 'ballgame.wav'