- alias: Disarm security alarm
  mode: restart
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'disarmed'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.back_door_alarm_sounding_blink, switch.back_door_alarm_arming_blink, switch.back_door_alarm_disarmed, switch.back_door_alarm_arming, switch.back_door_alarm_armed, switch.front_door_alarm_sounding_blink, switch.front_door_alarm_arming_blink, switch.front_door_alarm_disarmed, switch.front_door_alarm_arming, switch.front_door_alarm_armed
    - service: switch.turn_on
      data:
        entity_id: switch.back_door_alarm_disarmed, switch.front_door_alarm_disarmed
    - service: media_player.turn_off
      entity_id: media_player.all_devices
    - condition: template
      value_template: '{{ trigger.from_state.state != "armed_home" }}'
    - service: media_player.turn_on
      entity_id: media_player.all_devices
    - wait_template: "{{ is_state('media_player.all_devices', 'idle') }}"
    - service: var.set
      data:
        entity_id: var.volume_temp
        value_template: "{{ state_attr('media_player.all_devices', 'volume_level')| float | round(2)}}"
    - service: media_player.volume_set
      data:
        entity_id: media_player.all_devices
        volume_level: 0.5
    - service: media_player.play_media
      data:
        entity_id: media_player.all_devices
        media_content_id: 'http://192.168.0.2:8123/local/audio/success.mp3'
        media_content_type: music
    - wait_template: "{{ is_state('media_player.all_devices', 'playing') }}"
      timeout: "00:02:00"
    - wait_template: "{{ is_state('media_player.all_devices', 'idle') }}"
      timeout: "00:02:00"
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.all_devices
        volume_level: "{{ states('var.volume_temp')| float }}"
    - service: media_player.turn_off
      entity_id: media_player.all_devices
    - service: switch.turn_off
      data:
        entity_id: switch.noonlight_switch