- alias: dominos controller
  mode: restart
  trigger:
      - platform: event
        event_type: ifttt_webhook_received
        event_data:
          action: dominos_service
  condition:
    condition: state
    entity_id: var.mode
    state: 'home'
  action:
    - service: var.set
      data:
        entity_id: var.aurora_temp
        value_template: "{{ state_attr('light.nanoleaf', 'effect') }}"
    - service: light.turn_on
      data_template:
        entity_id: light.nanoleaf
        effect: >
          {% if trigger.event.data.stage == 'prepped' %}
            Progress 33
          {% elif trigger.event.data.stage == 'oven' %}
            Progress 66
          {% elif trigger.event.data.stage == 'quality' %}
            Progress 100
          {% else %}
            Progress 100 Wheel
          {% endif %}
    - delay:
        minutes: 1
    - condition: state
      entity_id: var.mode
      state: 'home'
    - service_template: >
        {%- if is_state('input_select.aurora_mode', 'Weather') -%}
        script.aurora_weather
        {%- elif is_state('input_select.aurora_mode', 'Manual') -%}
        script.aurora_manual
        {% endif %}