- alias: Send notification when sensor is opened
  mode: restart
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.front_door
        - binary_sensor.back_door
        - binary_sensor.wyze_group
        - binary_sensor.master_bedroom_window
        - binary_sensor.north_living_room_window
        - binary_sensor.south_living_room_window
        - binary_sensor.office_window
        - binary_sensor.south_kitchen_window
      to: 'on'
  action:
    - service: notify.living_room_tv
      data_template:
        message: "{{ trigger.to_state.name | capitalize }} has been opened"
    - service: notify.html5
      data_template:
        message: "{{ trigger.to_state.name | capitalize }} has been opened"