- alias: Send notification when dryer is done
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.dryer
  action:
    - service: notify.mobile_app_madisons_iphone
      data:
        message: "Dryer is done!"
        data:
          push:
            category: "laundry-done"
            thread-id: "laundry-reminder"
            sound: 'buzzer.wav'