- alias: Update ecobee mode on movement change
  mode: restart
  trigger:
      - platform: state
        entity_id:
          - group.home
          - var.mode
  action:
    - service: input_select.select_option
      data:
        entity_id: 
          - input_select.ecobee_modes
        option: >-
          {% if is_state('group.home','home') and is_state('var.mode','home') %}
          Home
          {% elif is_state('group.home','not_home') %}
          Away
          {% elif is_state('var.mode','sleep') and is_state('group.home','home') %}
          Sleep
          {% endif %}