- alias: Send notification if I have not taken my e
  mode: restart
  trigger:
    - platform: time
      at: '19:00:00'
    - platform: time
      at: '22:00:00'
    - platform: zone
      entity_id: device_tracker.madisons_iphone_app
      zone: zone.home
      event: enter
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.estrogen_status
      state: 'off'
    - condition: time
      after: '18:59:59'
      weekday:
      - thu
  action:
    - service: notify.mobile_app_madisons_iphone
      data:
        message: "Take your estrogen!"
        data:
          group: "estrogen-reminder"
          tag: "estrogen-reminder"
          push:
            sound: 'medical.wav'
          actions:
            - action: "DISMISS_E"
              title: "Taken"