- alias: Mark estrogen taken
  mode: restart
  trigger:
    - platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: estrogen_service
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: DISMISS_E
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.estrogen_status