- alias: Mark meds taken
  mode: restart
  trigger:
    - platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: meds_service
  action:
    service: script.medication_status