- alias: Set nap from ifttt
  trigger:
      platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: nap_service
  action:
    service: script.set_nap
    data_template:
      duration: '{{ trigger.event.data.duration }}'