- alias: Set laundry reminder
  mode: restart
  trigger:
      - platform: event
        event_type: ifttt_webhook_received
        event_data:
          action: laundry_service
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.laundry_reminder