- alias: Set staying up late
  mode: restart
  trigger:
      platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: staying_up_service
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.staying_up