- alias: Change living_room ac to off based on input select
  mode: restart
  trigger:
    - platform: state
      entity_id: input_select.living_room_ac_mode
      to: "Off"
  action:
    - service: rest_command.turn_off_living_room_ac

- alias: Change living_room ac to cool based on input select
  mode: restart
  trigger:
    - platform: state
      entity_id: input_select.living_room_ac_mode
      to: "Cool"
  action:
    - service: rest_command.turn_on_living_room_ac
    - service: rest_command.living_room_ac_mode
    - service: rest_command.living_room_ac_fan_mode
    - service: rest_command.living_room_ac_temperature_set

- alias: Change living_room ac to fan based on input select
  mode: restart
  trigger:
    - platform: state
      entity_id: input_select.living_room_ac_mode
      to: "Fan"
  action:
    - service: rest_command.turn_on_living_room_ac
    - service: rest_command.living_room_ac_mode
    - service: rest_command.living_room_ac_fan_mode

- alias: Change living_room ac to dry based on input select
  mode: restart
  trigger:
    - platform: state
      entity_id: input_select.living_room_ac_mode
      to: "Dry"
  action:
    - service: rest_command.turn_on_living_room_ac
    - service: rest_command.living_room_ac_mode
    - service: rest_command.living_room_ac_fan_mode
    - service: rest_command.living_room_ac_temperature_set