- alias: Lost connection with door or window sensor
  mode: parallel
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.front_door
        - binary_sensor.back_door
        - binary_sensor.wyze_group
        - binary_sensor.bedroom_window
        - binary_sensor.north_living_room_window
        - binary_sensor.south_living_room_window
        - binary_sensor.office_window
        - binary_sensor.south_kitchen_window
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.attributes.assumed_state == True }}"
  action:
    - service: notify.mobile_app_madisons_iphone
      data_template:
        title: "Lost Sensor"
        message: "Lost connection to {{ trigger.to_state.name | capitalize }}"
        data:
          apns_headers:
            'apns-collapse-id': 'lost-connection'
          push:
            thread-id: "lost-connection"
            critical: 1
            volume: 1.0