- alias: Low battery door or window sensor
  mode: parallel
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.front_door
        - binary_sensor.back_door
        - binary_sensor.east_dining_room_window
        - binary_sensor.west_dining_room_window
        - binary_sensor.master_bedroom_window
        - binary_sensor.guest_bedroom_window
        - binary_sensor.north_living_room_window
        - binary_sensor.south_living_room_window
        - binary_sensor.office_window
        - binary_sensor.south_kitchen_window
        - binary_sensor.west_kitchen_window
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.attributes.battery_level < 60 }}"
  action:
    - service: notify.mobile_app_madisons_iphone
      data_template:
        title: "Low Battery"
        subtitle: "{{ trigger.to_state.name | capitalize }} sensor battery is low."
        message: "Battery level: {{ trigger.to_state.attributes.battery_level }}%"
        data:
          apns_headers:
            'apns-collapse-id': 'low-battery'
          push:
            thread-id: "low-battery"
            critical: 1
            volume: 1.0