- alias: Send notification if I have not taken my medication
  mode: restart
  trigger:
    - platform: time
      at: '10:00:00'
    - platform: time
      at: '12:00:00'
    - platform: time
      at: '22:00:00'
#    - platform: zone
#      entity_id: device_tracker.madisons_iphone_app
#      zone: zone.home
#      event: enter
#  condition:
#    condition: and
#    conditions:
#    - condition: template
#      value_template: "{{ (states('counter.meds_counter') | int % 2) != 0 }}"
#    - condition: time
#      after: '18:59:59'
  condition: >-
    {% set meds_var = 'input_boolean.' + states('sensor.day_of_week') + '_meds_' + ('morning' if 0 <= (states('sensor.time')|regex_replace(find=':.*$', replace='', ignorecase=False)|int) <= 10 else '') + ('noon' if 11 <= (states('sensor.time')|regex_replace(find=':.*$', replace='', ignorecase=False)|int) <= 15 else '') + ('evening' if 15 <= (states('sensor.time')|regex_replace(find=':.*$', replace='', ignorecase=False)|int) <= 22 else '') %}
    {{ is_state(meds_var, 'off') }}
  action:
    - service: notify.mobile_app_madisons_iphone
      data:
        message: "Take your meds!"
        data:
          apns_headers:
            'apns-collapse-id': 'medication-reminder'
          push:
            category: "meds"
            thread-id: "medication-reminder"
            sound: 'medical.wav'
          action_data: 
            id: "meds"