- alias: Send notification if I have not taken my medication
  mode: restart
  trigger:
    - platform: time
      at: '10:00:00'
#    - platform: time
#      at: '12:00:00'
    - platform: time
      at: '22:00:00'
#    - platform: zone
#      entity_id: device_tracker.madisons_iphone_app
#      zone: zone.home
#      event: enter
  condition: >-
    {% if 7 <= (states('sensor.time')|regex_replace(find=':.*$', replace='', ignorecase=False)|int) <= 13 %}
      {% set meds_var = 'input_boolean.meds_morning' %}
    {% else %}
      {% set meds_var = 'input_boolean.meds_evening' %}
    {% endif %}
    {{ is_state(meds_var, 'off') }}
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.medication_lights_blinker
    - service: notify.mobile_app_madisons_iphone
      data:
        message: "Take your meds!"
        data:
          group: "medication-reminder"
          tag: "medication-reminder"
          push:
            sound: 'medical.wav'
          actions:
            - action: "DISMISS_MEDS"
              title: "Taken"