- alias: NFC Movie Tag Controller
  mode: restart
  trigger:
    platform: event
    event_type: tag_scanned
  condition: '{{ "3ecf3efe045a42abc48278d2a2f63a5c" in trigger.event.data.device_id }}'
  action:
  #  - service: persistent_notification.create
  #    data_template:
  #      message: 'NFC Tag for {{ trigger.event.data.tag_id }} scanned from {{ trigger.event.data.device_id }}. Casting from media-source://media_source/local/{{ trigger.event.data.tag_id }}.mp4'



#    - service: media_player.play_media
#      data:
#        media_content_type: video
#        media_content_id: media-source://media_source/local/{{ trigger.event.data.tag_id | replace("%20"," ") | replace("%E2%80%A2","•") | replace("%27","'") }}.mp4
#      target:
#        entity_id: media_player.living_room_chromecast
    - service: media_player.play_media
      data_template:
        media_content_type: movie
        media_content_id: >
          plex://{"library_name": "Movies", "title": "{{ trigger.event.data.tag_id | replace("%20"," ") | replace("%E2%80%A2","•") | replace("%27","'") }}"}
      target:
        entity_id: media_player.living_room_chromecast






#living room scanner id: 3ecf3efe045a42abc48278d2a2f63a5c
