- alias: Send iOS notification when cooler outside than inside
  mode: restart
  trigger:
    platform: template
    value_template: "{{ (state_attr('weather.home','temperature') < state_attr('climate.thermostat', 'current_temperature')) and ((state_attr('weather.home','humidity') < 60) or (state_attr('weather.home','wind_speed') > 10)) }}"
    for: "00:05:00"
  condition:
    - condition: numeric_state
      entity_id: "weather.home"
      attribute: temperature
      above: 21
    - condition: state
      entity_id:
        - binary_sensor.back_door
        - binary_sensor.front_door
        - binary_sensor.office_window
        - binary_sensor.vanity_room_window
        - binary_sensor.west_kitchen_window
        - binary_sensor.north_living_room_window
      state: "off"
    - condition: state
      entity_id: input_boolean.awake
      state: "on"
  action:
    - service: notify.mobile_app_madisons_iphone
      data_template:
        message: "It's nice out; you should open the windows!"
        data:
          group: "open-window"
          tag: "open-window"