- alias: Reset pills counter
  mode: restart
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: REFILL_PILLS
  action:
    - service: counter.reset
      entity_id: counter.meds_counter