######################################################################################
- alias: Start living room slider timer
  trigger:
    platform: state
    entity_id: input_number.living_room_brightness
  condition:
    - condition: template
      value_template: "{{ (now().timestamp() - states.light.living_room_lights.last_changed.timestamp()) > 1.5 }}"
  action:
    - service: timer.cancel
      entity_id: timer.living_room_slider
    - service: timer.start
      entity_id: timer.living_room_slider

- alias: Start living room light timer
  trigger:
    platform: state
    entity_id: light.living_room_lights
  condition:
    - condition: template
      value_template: "{{ (now().timestamp() - states.input_number.living_room_brightness.last_changed.timestamp()) > 1.5 }}"
  action:
    - service: timer.cancel
      entity_id: timer.living_room_light
    - service: timer.start
      entity_id: timer.living_room_light

- alias: Set living room brightness based on brightness slider
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.living_room_slider
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.living_room_lights
        brightness: "{{ (255 * (states('input_number.living_room_brightness') | int / 100)) | int }}"

- alias: Set living room brightness slider
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.living_room_light
  action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.living_room_brightness
          value: "{{ ((state_attr('light.living_room_lights','brightness')/255*100) if state_attr('light.living_room_lights','brightness') else 0) | int }}"
######################################################################################
- alias: Start bedroom slider timer
  trigger:
    platform: state
    entity_id: input_number.bedroom_brightness
  condition:
    - condition: template
      value_template: "{{ (now().timestamp() - states.light.bedroom_lights.last_changed.timestamp()) > 1.5 }}"
  action:
    - service: timer.cancel
      entity_id: timer.bedroom_slider
    - service: timer.start
      entity_id: timer.bedroom_slider

- alias: Start bedroom light timer
  trigger:
    platform: state
    entity_id: light.bedroom_lights
  condition:
    - condition: template
      value_template: "{{ (now().timestamp() - states.input_number.bedroom_brightness.last_changed.timestamp()) > 1.5 }}"
  action:
    - service: timer.cancel
      entity_id: timer.bedroom_light
    - service: timer.start
      entity_id: timer.bedroom_light

- alias: Set bedroom brightness based on brightness slider
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bedroom_slider
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_lights
        brightness: "{{ (255 * (states('input_number.bedroom_brightness') | int / 100)) | int }}"

- alias: Set bedroom brightness slider
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bedroom_light
  action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.bedroom_brightness
          value: "{{ ((state_attr('light.bedroom_lights','brightness')/255*100) if state_attr('light.bedroom_lights','brightness') else 0) | int }}"
######################################################################################
- alias: Start bathroom slider timer
  trigger:
    platform: state
    entity_id: input_number.bathroom_brightness
  condition:
    - condition: template
      value_template: "{{ (now().timestamp() - states.light.bathroom_lights.last_changed.timestamp()) > 1.5 }}"
  action:
    - service: timer.cancel
      entity_id: timer.bathroom_slider
    - service: timer.start
      entity_id: timer.bathroom_slider

- alias: Start bathroom light timer
  trigger:
    platform: state
    entity_id: light.bathroom_lights
  condition:
    - condition: template
      value_template: "{{ (now().timestamp() - states.input_number.bathroom_brightness.last_changed.timestamp()) > 1.5 }}"
  action:
    - service: timer.cancel
      entity_id: timer.bathroom_light
    - service: timer.start
      entity_id: timer.bathroom_light

- alias: Set bathroom brightness based on brightness slider
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bathroom_slider
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bathroom_lights
        brightness: "{{ (255 * (states('input_number.bathroom_brightness') | int / 100)) | int }}"

- alias: Set bathroom brightness slider
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bathroom_light
  action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.bathroom_brightness
          value: "{{ ((state_attr('light.bathroom_lights','brightness')/255*100) if state_attr('light.bathroom_lights','brightness') else 0) | int }}"
######################################################################################
- alias: Start kitchen slider timer
  trigger:
    platform: state
    entity_id: input_number.kitchen_brightness
  condition:
    - condition: template
      value_template: "{{ (now().timestamp() - states.light.kitchen_lights.last_changed.timestamp()) > 1.5 }}"
  action:
    - service: timer.cancel
      entity_id: timer.kitchen_slider
    - service: timer.start
      entity_id: timer.kitchen_slider

- alias: Start kitchen light timer
  trigger:
    platform: state
    entity_id: light.kitchen_lights
  condition:
    - condition: template
      value_template: "{{ (now().timestamp() - states.input_number.kitchen_brightness.last_changed.timestamp()) > 1.5 }}"
  action:
    - service: timer.cancel
      entity_id: timer.kitchen_light
    - service: timer.start
      entity_id: timer.kitchen_light

- alias: Set kitchen brightness based on brightness slider
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.kitchen_slider
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kitchen_lights
        brightness: "{{ (255 * (states('input_number.kitchen_brightness') | int / 100)) | int }}"

- alias: Set kitchen brightness slider
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.kitchen_light
  action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.kitchen_brightness
          value: "{{ ((state_attr('light.kitchen_lights','brightness')/255*100) if state_attr('light.kitchen_lights','brightness') else 0) | int }}"
######################################################################################
- alias: Start dining area slider timer
  trigger:
    platform: state
    entity_id: input_number.dining_area_brightness
  condition:
    - condition: template
      value_template: "{{ (now().timestamp() - states.light.dining_area_lights.last_changed.timestamp()) > 1.5 }}"
  action:
    - service: timer.cancel
      entity_id: timer.dining_area_slider
    - service: timer.start
      entity_id: timer.dining_area_slider

- alias: Start dining area light timer
  trigger:
    platform: state
    entity_id: light.dining_area_lights
  condition:
    - condition: template
      value_template: "{{ (now().timestamp() - states.input_number.dining_area_brightness.last_changed.timestamp()) > 1.5 }}"
  action:
    - service: timer.cancel
      entity_id: timer.dining_area_light
    - service: timer.start
      entity_id: timer.dining_area_light

- alias: Set dining area brightness based on brightness slider
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.dining_area_slider
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.dining_area_lights
        brightness: "{{ (255 * (states('input_number.dining_area_brightness') | int / 100)) | int }}"

- alias: Set dining area brightness slider
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.dining_area_light
  action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.dining_area_brightness
          value: "{{ ((state_attr('light.dining_area_lights','brightness')/255*100) if state_attr('light.dining_area_lights','brightness') else 0) | int }}"
######################################################################################
- alias: Start entryway slider timer
  trigger:
    platform: state
    entity_id: input_number.entryway_brightness
  condition:
    - condition: template
      value_template: "{{ (now().timestamp() - states.light.entryway_lights.last_changed.timestamp()) > 1.5 }}"
  action:
    - service: timer.cancel
      entity_id: timer.entryway_slider
    - service: timer.start
      entity_id: timer.entryway_slider

- alias: Start entryway light timer
  trigger:
    platform: state
    entity_id: light.entryway_lights
  condition:
    - condition: template
      value_template: "{{ (now().timestamp() - states.input_number.entryway_brightness.last_changed.timestamp()) > 1.5 }}"
  action:
    - service: timer.cancel
      entity_id: timer.entryway_light
    - service: timer.start
      entity_id: timer.entryway_light

- alias: Set entryway brightness based on brightness slider
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.entryway_slider
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.entryway_lights
        brightness: "{{ (255 * (states('input_number.entryway_brightness') | int / 100)) | int }}"

- alias: Set entryway brightness slider
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.entryway_light
  action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.entryway_brightness
          value: "{{ ((state_attr('light.entryway_lights','brightness')/255*100) if state_attr('light.entryway_lights','brightness') else 0) | int }}"