- alias: Set aurora effects list on startup
  trigger:
    - platform: homeassistant
      event: start
  action:
    - wait_template: "{{ not is_state('light.nanoleaf', 'unknown') }}"
      timeout: '00:10:00'
    - service: rest_command.set_aurora_effects