- alias: Set bedroom ac temperature based on climate
  trigger:
    - platform: state
      entity_id: sensor.climate_bedroom_set_temperature
  action:
    - service: rest_command.bedroom_ac_temperature_set