- alias: Start washing machine timer
  mode: restart
  trigger:
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: START_WASHER
  action:
    service: timer.start
    entity_id: timer.laundry