- alias: Start dryer timer
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: START_DRYER
  action:
    service: timer.start
    entity_id: timer.dryer