- alias: Start dryer timer
  mode: restart
  trigger:
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: START_DRYER
  action:
    service: timer.start
    entity_id: timer.dryer