- alias: Start washing machine timer
  mode: restart
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: START_WASHER
  action:
    service: timer.start
    entity_id: timer.laundry