- alias: System variables info tab controller armond
  mode: restart
  trigger:
      - platform: state
        entity_id: input_boolean.system_variables_armond
        to: "on"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: 
          - input_boolean.system_disabled_automations_armond
          - input_boolean.system_running_automations_armond
          - input_boolean.system_running_scripts_armond
          - input_boolean.system_running_timers_armond
          - input_boolean.system_alerts_armond
          - input_boolean.system_groups_armond
    - service: input_select.select_option
      data_template:
        entity_id: input_select.system_info_tab_armond
        option: "system_variables"
        
- alias: System disabled automations info tab controller armond
  mode: restart
  trigger:
      - platform: state
        entity_id: input_boolean.system_disabled_automations_armond
        to: "on"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: 
          - input_boolean.system_variables_armond
          - input_boolean.system_running_automations_armond
          - input_boolean.system_running_scripts_armond
          - input_boolean.system_running_timers_armond
          - input_boolean.system_alerts_armond
          - input_boolean.system_groups_armond
    - service: input_select.select_option
      data_template:
        entity_id: input_select.system_info_tab_armond
        option: "system_disabled_automations"
        
- alias: System running timers info tab controller armond
  mode: restart
  trigger:
      - platform: state
        entity_id: input_boolean.system_running_timers_armond
        to: "on"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: 
          - input_boolean.system_variables_armond
          - input_boolean.system_running_automations_armond
          - input_boolean.system_running_scripts_armond
          - input_boolean.system_disabled_automations_armond
          - input_boolean.system_alerts_armond
          - input_boolean.system_groups_armond
    - service: input_select.select_option
      data_template:
        entity_id: input_select.system_info_tab_armond
        option: "system_running_timers"
        
- alias: System running scripts info tab controller armond
  mode: restart
  trigger:
      - platform: state
        entity_id: input_boolean.system_running_scripts_armond
        to: "on"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: 
          - input_boolean.system_disabled_automations_armond
          - input_boolean.system_running_automations_armond
          - input_boolean.system_variables_armond
          - input_boolean.system_running_timers_armond
          - input_boolean.system_alerts_armond
          - input_boolean.system_groups_armond
    - service: input_select.select_option
      data_template:
        entity_id: input_select.system_info_tab_armond
        option: "system_running_scripts"
        
- alias: System running automations info tab controller armond
  mode: restart
  trigger:
      - platform: state
        entity_id: input_boolean.system_running_automations_armond
        to: "on"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: 
          - input_boolean.system_disabled_automations_armond
          - input_boolean.system_variables_armond
          - input_boolean.system_running_scripts_armond
          - input_boolean.system_running_timers_armond
          - input_boolean.system_alerts_armond
          - input_boolean.system_groups_armond
    - service: input_select.select_option
      data_template:
        entity_id: input_select.system_info_tab_armond
        option: "system_running_automations"

- alias: System alerts info tab controller armond
  mode: restart
  trigger:
      - platform: state
        entity_id: input_boolean.system_alerts_armond
        to: "on"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: 
          - input_boolean.system_disabled_automations_armond
          - input_boolean.system_variables_armond
          - input_boolean.system_running_scripts_armond
          - input_boolean.system_running_timers_armond
          - input_boolean.system_running_automations_armond
          - input_boolean.system_groups_armond
    - service: input_select.select_option
      data_template:
        entity_id: input_select.system_info_tab_armond
        option: "system_alerts"

- alias: System groups info tab controller armond
  mode: restart
  trigger:
      - platform: state
        entity_id: input_boolean.system_groups_armond
        to: "on"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: 
          - input_boolean.system_disabled_automations_armond
          - input_boolean.system_variables_armond
          - input_boolean.system_running_scripts_armond
          - input_boolean.system_running_timers_armond
          - input_boolean.system_running_automations_armond
          - input_boolean.system_alerts_armond
    - service: input_select.select_option
      data_template:
        entity_id: input_select.system_info_tab_armond
        option: "system_groups"




- alias: system none mode switches controller armond
  mode: restart
  trigger:
      - platform: state
        entity_id: input_boolean.system_running_automations_armond
        to: "off"
      - platform: state
        entity_id: input_boolean.system_disabled_automations_armond
        to: "off"
      - platform: state
        entity_id: input_boolean.system_running_scripts_armond
        to: "off"
      - platform: state
        entity_id: input_boolean.system_variables_armond
        to: "off"
      - platform: state
        entity_id: input_boolean.system_running_timers_armond
        to: "off"
      - platform: state
        entity_id: input_boolean.system_alerts_armond
        to: "off"
      - platform: state
        entity_id: input_boolean.system_groups_armond
        to: "off"
  condition:
    condition: template
    value_template: "{{ is_state('input_boolean.system_running_scripts_armond','off') and is_state('input_boolean.system_running_automations_armond','off') and is_state('input_boolean.system_disabled_automations_armond','off') and is_state('input_boolean.system_variables_armond','off') and is_state('input_boolean.system_running_timers_armond','off') and is_state('input_boolean.system_alerts_armond','off') and is_state('input_boolean.system_groups_armond','off') }}"
  action:
    - service: input_boolean.turn_on
      data_template:
        entity_id: "{{trigger.entity_id}}"
        
- alias: input select system info switches
  mode: restart
  trigger:
      - platform: state
        entity_id: input_select.system_info_tab_armond
  action:
    - service: input_boolean.turn_on
      data_template:
        entity_id: "input_boolean.{{ states('input_select.system_info_tab') }}_armond"