- alias: Turn off tank lights in the evening
  mode: restart
  trigger:
    platform: sun
    event: sunset
  action:
    - service: switch.turn_off
      entity_id: switch.aquarium_day
    - service: switch.turn_on
      entity_id: switch.aquarium_night