- alias: Turn on tank lights in the morning
  mode: restart
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: switch.turn_on
      entity_id: switch.aquarium_day
    - service: switch.turn_off
      entity_id: switch.aquarium_night