- alias: Turn on tank lights in the morning
  mode: restart
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: light.turn_on
      entity_id: light.aquarium_day
    - service: light.turn_off
      entity_id: light.aquarium_night