- alias: Turn off tank lights in the evening
  mode: restart
  trigger:
    platform: sun
    event: sunset
  action:
    - service: light.turn_off
      entity_id: light.aquarium_day
    - service: light.turn_on
      entity_id: light.aquarium_night