- alias: Text friends when I get home
  mode: restart
  trigger:
    - platform: zone
      entity_id: device_tracker.madisons_iphone_app
      zone: zone.home
      event: enter
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.text_brianna
        state: 'on'
      - condition: state
        entity_id: input_boolean.text_lor
        state: 'on'
      - condition: state
        entity_id: input_boolean.text_mom
        state: 'on'
      - condition: state
        entity_id: input_boolean.text_armond
        state: 'on'
      - condition: state
        entity_id: input_boolean.text_claire
        state: 'on'
      - condition: state
        entity_id: input_boolean.text_krista
        state: 'on'
  action:
    - service: script.text_brianna_home
    - service: script.text_lor_home
    - service: script.text_mom_home
    - service: script.text_armond_home
    - service: script.text_claire_home
    - service: script.text_krista_home
    - service: input_boolean.turn_off
      entity_id: input_boolean.text_brianna
    - service: input_boolean.turn_off
      entity_id: input_boolean.text_lor
    - service: input_boolean.turn_off
      entity_id: input_boolean.text_mom
    - service: input_boolean.turn_off
      entity_id: input_boolean.text_armond
    - service: input_boolean.turn_off
      entity_id: input_boolean.text_claire
    - service: input_boolean.turn_off
      entity_id: input_boolean.text_krista