- alias: Travel bike mode switches controller Madison
  mode: restart
  trigger:
      - platform: state
        entity_id: input_boolean.travel_bike_madison
        to: "on"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: 
          - input_boolean.travel_transit_madison
          - input_boolean.travel_drive_madison
          - input_boolean.travel_walk_madison
          - input_boolean.travel_uber_madison
    - service: input_select.select_option
      data_template:
        entity_id: input_select.travel_mode_madison
        option: "Bike"
        
- alias: Travel transit mode switches controller madison
  mode: restart
  trigger:
      - platform: state
        entity_id: input_boolean.travel_transit_madison
        to: "on"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: 
          - input_boolean.travel_bike_madison
          - input_boolean.travel_drive_madison
          - input_boolean.travel_walk_madison
          - input_boolean.travel_uber_madison
    - service: input_select.select_option
      data_template:
        entity_id: input_select.travel_mode_madison
        option: "Transit"
        
- alias: Travel uber mode switches controller madison
  mode: restart
  trigger:
      - platform: state
        entity_id: input_boolean.travel_uber_madison
        to: "on"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: 
          - input_boolean.travel_bike_madison
          - input_boolean.travel_drive_madison
          - input_boolean.travel_walk_madison
          - input_boolean.travel_transit_madison
    - service: input_select.select_option
      data_template:
        entity_id: input_select.travel_mode_madison
        option: "Uber"
        
- alias: Travel walk mode switches controller madison
  mode: restart
  trigger:
      - platform: state
        entity_id: input_boolean.travel_walk_madison
        to: "on"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: 
          - input_boolean.travel_transit_madison
          - input_boolean.travel_drive_madison
          - input_boolean.travel_bike_madison
          - input_boolean.travel_uber_madison
    - service: input_select.select_option
      data_template:
        entity_id: input_select.travel_mode_madison
        option: "Walk"
        
- alias: Travel drive mode switches controller madison
  mode: restart
  trigger:
      - platform: state
        entity_id: input_boolean.travel_drive_madison
        to: "on"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: 
          - input_boolean.travel_transit_madison
          - input_boolean.travel_bike_madison
          - input_boolean.travel_walk_madison
          - input_boolean.travel_uber_madison
    - service: input_select.select_option
      data_template:
        entity_id: input_select.travel_mode_madison
        option: "Drive"
        
- alias: Travel none mode switches controller madison
  mode: restart
  trigger:
      - platform: state
        entity_id: input_boolean.travel_drive_madison
        to: "off"
      - platform: state
        entity_id: input_boolean.travel_transit_madison
        to: "off"
      - platform: state
        entity_id: input_boolean.travel_walk_madison
        to: "off"
      - platform: state
        entity_id: input_boolean.travel_bike_madison
        to: "off"
      - platform: state
        entity_id: input_boolean.travel_uber_madison
        to: "off"
  condition:
    condition: template
    value_template: "{{ is_state('input_boolean.travel_walk_madison','off') and is_state('input_boolean.travel_drive_madison','off') and is_state('input_boolean.travel_transit_madison','off') and is_state('input_boolean.travel_bike_madison','off') and is_state('input_boolean.travel_uber_madison','off') }}"
  action:
    - service: input_boolean.turn_on
      data_template:
        entity_id: "{{trigger.entity_id}}"
        
- alias: input select travel switches madison
  mode: restart
  trigger:
      - platform: state
        entity_id: input_select.travel_mode_madison
  action:
    - service: input_boolean.turn_on
      data_template:
        entity_id: "input_boolean.travel_{{ states('input_select.travel_mode') | lower }}_madison"