###TODO###
- alias: Turn off devices when away
  initial_state: true
  mode: restart
  trigger:
    platform: state
    entity_id: group.home
    to: 'not_home'
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.announce_time
    - service: light.turn_off
      target:
        entity_id: light.nanoleaf
    - service: light.turn_off
      target:
        entity_id: light.main_lights
    - service: light.turn_off
      target:
        entity_id: light.fairy_lights
#    - service: switch.turn_off
#      target:
#        entity_id: switch.air_freshener
#    - service: script.turn_off_tv
#    - service: script.turn_off_vanity
#    - service: script.turn_off_diffuser