- alias: Turn on fairy lights sunset
  mode: restart
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: var.mode
        state: 'away'
  action:
    - service: light.turn_on
      target:
        entity_id: light.fairy_lights