- alias: Turn on lights when I get home at night
  initial_state: true
  mode: restart
  trigger:
    - platform: zone
      entity_id: device_tracker.madisons_iphone_app
      zone: zone.home
      event: enter
    - platform: zone
      entity_id: device_tracker.armonds_iphone_app
      zone: zone.home
      event: enter
  action:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - service: hue.hue_activate_scene
      data:
        group_name: "Dining room"
        scene_name: "Bright"
    - service: hue.hue_activate_scene
      data:
        group_name: "Kitchen"
        scene_name: "Bright"