- alias: Turn on lights when I get home at night
  initial_state: true
  mode: restart
  trigger:
    - platform: zone
      entity_id: device_tracker.madisons_iphone_app
      zone: zone.home
      event: enter
    - platform: zone
      entity_id: device_tracker.armonds_iphone_app
      zone: zone.home
      event: enter
  action:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - service: scene.turn_on
      target:
        entity_id: scene.dining_room_bright
    - service: scene.turn_on
      target:
        entity_id: scene.kitchen_bright