- alias: Turn off devices when away
  initial_state: true
  trigger:
    platform: state
    entity_id: var.mode
    to: 'away'
  action:
    - service: light.turn_off
      entity_id: light.nanoleaf
    - service: light.turn_off
      entity_id: light.entry_way_2
    - service: light.turn_off
      entity_id: light.bathroom_6
    - service: light.turn_off
      entity_id: light.bedroom_4
    - service: light.turn_off
      entity_id: light.bedroom_closet_2
    - service: light.turn_off
      entity_id: light.kitchen_4
    - service: light.turn_off
      entity_id: light.dining_area_4
    - service: light.turn_off
      entity_id: light.coat_closet_2
    - service: light.turn_off
      entity_id: light.desktop
    - service: switch.turn_off
      entity_id: switch.air_freshener
    - service: script.turn_off_tv
    - service: script.turn_off_vanity
    - service: script.turn_off_diffuser
    - service: input_select.select_option
      data_template:
        entity_id: input_select.living_room_ac_mode
        option: "Off"
    - service: input_select.select_option
      data_template:
        entity_id: input_select.bedroom_ac_mode
        option: "Off"