###TODO###
- alias: Turn off devices when away
  initial_state: true
  mode: restart
  trigger:
    platform: state
    entity_id: group.home
    to: 'not_home'
  action:
    - service: light.turn_off
      entity_id: light.nanoleaf
    - service: light.turn_off
      entity_id: light.main_lights
    - service: light.turn_off
      entity_id: light.fairy_lights
    - service: switch.turn_off
      entity_id: switch.air_freshener
    - service: script.turn_off_tv
#    - service: script.turn_off_vanity
#    - service: script.turn_off_diffuser