- alias: Update travel time
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.travel_update_trigger
      to: "True"
    - platform: state
      entity_id: calendar.personal_trigger
    - platform: state
      entity_id: input_select.travel_mode
    - platform: state
      entity_id: input_boolean.staying_home
  action:
    - service: script.update_travel_time
    - service: homeassistant.update_entity
      entity_id: sensor.travel_update_trigger
    - service: homeassistant.update_entity
      entity_id: sensor.google_geocode