- alias: Update travel time armond
  initial_state: true
  mode: restart
  trigger:
    - platform: state
      entity_id: sensor.travel_update_trigger_armond
      to: "True"
    - platform: state
      entity_id: calendar.armond_trigger
    - platform: state
      entity_id: input_select.travel_mode_armond
    - platform: state
      entity_id: input_boolean.staying_home_armond
  action:
    - service: script.update_travel_time_armond
    - service: homeassistant.update_entity
      entity_id: sensor.travel_update_trigger_armond
    - service: homeassistant.update_entity
      entity_id: sensor.armond_geocode