esphome:
  name: medication-lights

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "9e1ba0f2aabf360080b922a23943e781"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Medication-Lights"
    password: "7S4eWPDZ3akF"

captive_portal:
    
switch:
  - platform: gpio
    name: "Medication Lights"
    pin: 0
    id: relay
    
  - platform: template
    name: "Medication Lights Blinker"
    optimistic: yes
    id: blinking
    turn_on_action:
    - while:
        condition:
          lambda: 'return true;'
        then:
        - switch.turn_on: relay
        - delay: 1s 
        - switch.turn_off: relay
        - delay: 1s
    turn_off_action:
    - switch.turn_off: relay